name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build standalone binary for Ubuntu
      run: |
        pyinstaller --name=crs_transform --onefile --windowed main.py
      if: matrix.os == 'ubuntu-latest'

    - name: Build standalone binary for Windows
      run: |
        pyinstaller --name=crs_transform --onefile --windowed main.py
      if: matrix.os == 'windows-latest'

    - name: Create zip archive for Ubuntu
      run: |
        if [ -d dist ]; then
          zip -r crs_transform_ubuntu.zip dist
        else
          echo "Error: dist directory not found"
          exit 1
        fi
      if: matrix.os == 'ubuntu-latest'

    - name: Create zip archive for Windows
      run: |
        if (Test-Path dist) {
          Compress-Archive -Path dist -DestinationPath crs_transform_windows.zip
        } else {
          Write-Error "dist folder not found"
          exit 1
        }
      if: matrix.os == 'windows-latest'

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: crs_transform
        path: |
          crs_transform_ubuntu.zip
          crs_transform_windows.zip
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        body: |
          This is the first release of myapp.
        draft: false
        prerelease: false
    
